# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Rad Dishes
tagline:          
url:              http://rad-dish.es
paginate:         
url:          	  http://darrendnub.github.io/rad-dishes
author:
  name:           Darren Wong
  url:            https://twitter.com/darrendub
  email:          darrendavenwong@gmail.com

# Navigation Elements
pages_list:       
  About: '/about'         
